- Cargo.lock
- Cargo.toml
- src/find/mod.rs
We should probably publish to `crates.io` at some point.
> Use walkdir from crates.io rather than a git fork

- src/find/matchers/exec.rs
- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/matchers/name.rs
- src/find/matchers/perm.rs
- src/find/matchers/printer.rs
- src/find/matchers/prune.rs
- src/find/matchers/size.rs
- src/find/matchers/time.rs
- src/find/matchers/type_matcher.rs
- src/find/mod.rs
The keyword is needed for trait objects and is intended to improve
readability.
https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html
> Add the 'dyn' keyword where necessary

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/find/matchers/delete.rs
- src/find/matchers/exec.rs
- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/matchers/perm.rs
- src/find/matchers/prune.rs
- src/find/matchers/size.rs
- src/find/matchers/time.rs
- src/find/matchers/type_matcher.rs
- src/find/mod.rs
- src/testing/commandline/main.rs
- tests/common/test_helpers.rs
- tests/find_cmd_tests.rs
This takes @Arcterus's implementation of -delete and fixes a few issues in hopes of getting it added.
The most significant change other than the tests is a bit of rework on skipping the working dir. The existing code tried to skip the working dir in general, which isn't quite right. Only a literal "." is supposed to be skipped, which is actually simpler to do.
Safely testing that behavior was a little tricky from the unit test perspective, so I took the liberty of adding some general integration tests, which I think provide some value on their own and are an easier context from which to test the dot thing.
Also included are a bunch of trivial compiler warning fixes (was rather noisy).
> Implement -delete (#13) with tests (supersedes PR #22)

- src/find/mod.rs
- Error `clippy::unnecessary-wraps` that is failing ci
- Error `clippy::borrowed-box` that was ignored
> Fix clippy errors in src/find/mod.rs

- .gitignore
- src/find/matchers/type_matcher.rs
Now all file types except for D (door on Solaris) are supported.
This is not blocked by the support of -H -L -P flags.
Because the default behavior of GNU find is "Never follow symbolic links".
```
-P     Never follow symbolic links.  This is the default behaviour.  When find examines or prints information
about  files, and the file is a symbolic link, the information used shall be taken from the properties
of the symbolic link itself.
```
> type_matcher.rs: add support for: l b c p s

- src/find/matchers/mod.rs
> Make multi-exec only match {} + with nothing in between

- src/find/matchers/exec.rs
- tests/exec_unit_tests.rs
> exec: Handle parent directories more carefully

- .github/workflows/compat.yml
- util/build-bfs.sh
This is the first half of the needed changes to set up automated
compatibility tests against GNU findutils and bfs, handling the uploads
of the build logs and JSON results. The workflow itself is heavily based
on the one from uutils/coreutils:
https://github.com/uutils/coreutils/blob/main/.github/workflows/GnuTests.yml
but with various cleanups & tweaks to better suit findutils.
This does *not* include the actual regression comparisons, because those
will only pass once archives of these files are up on the main branch.
Ref #128
<hr>
Like the commit message mentions, this is the first half of the changes, because [the second half](https://github.com/uutils/findutils/compare/main...refi64:compat-tests-2?expand=1) needs …
> Add initial parts of automated compatibility tests

- src/find/matchers/mod.rs
- src/find/matchers/printer.rs
- src/find/mod.rs
<hr>
I admittedly had this ready for a bit now, but I knew it would have merge conflicts with #120 so just waited until that was in first
> Add support for -print0

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/find/matchers/mod.rs
- src/find/matchers/regex.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
This adds support for -regextype, -regex, and -iregex, using Oniguruma
to implement support for the Emacs, grep, POSIX basic, and POSIX
extended regex types.
<hr>
Meta note: I'm not sure if it would be preferred to have this behind a feature, since oniguruma *is* a C dependency, or if `regex` should be removed instead due to functionality overlap.
> Add support for regex matching

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/testing/commandline/main.rs
- src/xargs/main.rs
- src/xargs/mod.rs
- tests/xargs_tests.rs
- util/build-gnu.sh
This includes much of the core xargs functionality, with the following
notable exceptions:
- Parallel execution (`-P`): This option currently just does
nothing, that way anything that passes -P can at least run without a
notable behavior shift (other than simply being slower).
- Replacement strings (`-I`): This can easily be worked around via an
intermediate shell invocation (e.g. `xargs -L1 sh -c 'do-things-with
$@' --`).
- EOF strings (`-E`): I've honestly never seen this actually used,
though it would not be particularly difficult to implement given the
current architecture.
Closes #37
**This has not been tested with Windows CI yet and also depends on #120, so I've marked it as a draft.**
> Add an initial implementation of xargs

- .github/workflows/compat.yml
By default, artifacts are only downloaded from the latest successful
workflow, meaning that, if the compat tests regressed, then it is
impossible to compare against the new current state. This isn't a
perfect solution, but I believe it should by far be "good enough" for
these purposes.
> Fix compat tests not using the latest workflow

- Cargo.lock
- Cargo.toml
This version includes the needed filesystem type detection fix.
> Update uucore to 0.0.12

- src/find/matchers/mod.rs
- src/find/matchers/name.rs
- src/find/mod.rs
> Add support for -lname / -ilname

- src/find/matchers/mod.rs
- src/find/mod.rs
Unfortunately, the nature of this makes it incredibly hard to test for
in CI; not even BFS's massive test suite covers it. That being said,
it's a simple enough addition that the risk it incurs hopefully
shouldn't be too large.
> Add support for -xdev

- src/find/matchers/prune.rs
This matches up with the behavior of GNU findutils, as documented in its
man page:
> **if the file is a directory**, do not descend into it
> Avoid skipping the entire directory if a file hits -prune

- Cargo.lock
- Cargo.toml
- src/find/main.rs
- src/find/matchers/glob.rs
- src/find/matchers/lname.rs
- src/find/matchers/mod.rs
- src/find/matchers/name.rs
- src/find/matchers/path.rs
- src/find/matchers/regex.rs
- src/lib.rs
- util/build-bfs.sh
This implements POSIX-compliant globs for `-name`, `-lname`, and the new `-path`.  I couldn't find an existing crate that provided `fnmatch()` semantics exactly, so I implemented the conversion to POSIX regexes myself.
> POSIX compliant globs

- Cargo.toml
- src/find/matchers/mod.rs
- src/find/matchers/perm.rs
- tests/find_cmd_tests.rs
> find: Use the uucore mode parsing implementation for -perm

- .github/workflows/compat.yml
- util/build-bfs.sh
The latest bfs properly groups the --sudo tests, so we can test things
that require root like -xdev.
> ci: Update bfs testsuite to version 2.6

- Cargo.lock
- Cargo.toml
- src/find/matchers/printf.rs
Use nix's version of mkfifo instead, which lets us easily access the
errors and then fail with more information than the FIFO mysteriously
not appearing.
Ref. #177.
> find: Don't swallow mkfifo errors in the tests

- src/find/matchers/printf.rs
`this expression borrows a value the compiler would automatically borrow`
> Fix a clippy warning

- src/find/matchers/lname.rs
- src/find/matchers/name.rs
- src/find/matchers/printf.rs
- src/find/matchers/type_matcher.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
- Issue stated in [Issues #226](https://github.com/uutils/findutils/issues/226)
#226 
Used assert! statement instead of alert,  to indicate a failed condition without stopping the program immediately.
```
if e.kind() != ErrorKind::AlreadyExists {
assert!(false, "Failed to create sym link: {:?}", e);
}
```
> implemented assert! for resolving warning panic!

- .gitignore
- docs/src/logo.svg
- docs/src/oranda.css
- oranda.json
(I should have done this from my own fork, but I only noticed that once I was done :) )
Simplified version of what we already did for `coreutils`. We could expand this later with `mdbook` docs here too. The idea for now is just to have a simple page to link to from the uutils homepage (I'm working on a PR for the uutils.github.io repo).
> initial oranda setup

- src/find/matchers/delete.rs
- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/matchers/printf.rs
- src/find/matchers/size.rs
- src/find/matchers/type_matcher.rs
- src/find/mod.rs
- src/xargs/mod.rs
- tests/xargs_tests.rs
> Fix clippy warning on 'format!' strings

- Cargo.lock
- Cargo.toml
This PR sets `default-features = false` for `onig` in `Cargo.toml`. Without this setting, I get the following error when trying to run `cargo run --bin find find --help`:
```
error: failed to run custom build command for `onig_sys v69.8.1`
Caused by:
process didn't exit successfully: `/home/dho/projects/findutils/target/debug/build/onig_sys-0c27472ef7fa82d9/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=RUSTONIG_DYNAMIC_LIBONIG
cargo:rerun-if-env-changed=RUSTONIG_STATIC_LIBONIG
cargo:rerun-if-env-changed=RUSTONIG_SYSTEM_LIBONIG
--- stderr
thread 'main' panicked at /home/dho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.60/src/fallback.rs:791:9:
"OnigValue_struct_(unnamed_at_oniguruma/src/oniguruma_h_786_3)" is not a valid Ident
note: …
```
> Cargo.toml: set "default-features = false" for onig

- Cargo.lock
This PR bumps `wasm-bindgen` from `0.2.82` to `0.2.91` and thus removing one of the two `syn` versions we use.
> Bump wasm-bindgen from 0.2.82 to 0.2.91

- src/find/matchers/printf.rs
This PR fixes two deprecation warnings from `chrono` because the `ymd()` and `and_hms_nano()` functions have been deprecated.
> Fix deprecation warnings from `chrono` in test

- Cargo.lock
This PR bumps `parking_lot_core` from `0.9.3` to `0.9.9` to get rid of one of the three versions of `windows-sys` we use.
> Bump parking_lot_core from 0.9.3 to 0.9.9

- src/xargs/mod.rs
This PR fixes some "unnecessary else block" warnings shown by rustanalyzer.
> xargs: remove unnecessary else blocks

- Cargo.lock
This PR bumps `clap` from `4.4.6` to `4.4.18`, the most recent version with a MSRV of `1.70`.
> Bump clap from 4.4.6 to 4.4.18

- src/xargs/mod.rs
- tests/xargs_tests.rs
This PR renames `--size` to `--max-chars` because in GNU `xargs` the long form of `-s` is `--max-chars` and not `--size`.
> xargs: rename `--size` to `--max-chars`

- src/find/matchers/access.rs
- src/find/matchers/empty.rs
- src/find/matchers/glob.rs
- src/find/matchers/lname.rs
- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/matchers/name.rs
- src/find/matchers/path.rs
- src/find/matchers/perm.rs
- src/find/matchers/printer.rs
- src/find/matchers/printf.rs
- src/find/matchers/prune.rs
- src/find/matchers/quit.rs
- src/find/matchers/regex.rs
- src/find/matchers/size.rs
- src/find/matchers/stat.rs
- src/find/matchers/time.rs
- src/find/matchers/type_matcher.rs
- src/find/mod.rs
- tests/common/test_helpers.rs
This PR fixes many "item x imported redundantly" warnings I noticed in https://github.com/uutils/findutils/actions/runs/8043426350/job/21965483934?pr=324
> find: fix "item x imported redundantly" warnings

- src/find/matchers/time.rs
- src/find/matchers/type_matcher.rs
This PR fixes two clippy warnings from the [useless_asref](https://rust-lang.github.io/rust-clippy/master/index.html#/useless_asref) and [unnecessary_mut_passed](https://rust-lang.github.io/rust-clippy/master/index.html#/unnecessary_mut_passed) lints.
> find: fix two clippy warnings

- Cargo.toml
This PR specifies the complete `chrono` version to get rid of the "maybe insecure" shown in the "dependencies" badge.
> Cargo.toml: specify complete chrono version

- .github/workflows/compat.yml
This PR names the upload steps so we don't have "Run actions/upload-artifact@v4" listed twice when looking at the jobs of the `compat` workflow (see, for example, https://github.com/uutils/findutils/actions/runs/8499267868/job/23301772648?pr=323).
> ci: name upload steps

- Cargo.lock
- Cargo.toml
- src/xargs/mod.rs
- tests/xargs_tests.rs
> xargs: Implement replace / -I (Closes: #310)

- src/find/matchers/delete.rs
- src/find/matchers/exec.rs
- src/find/matchers/glob.rs
- src/find/matchers/lname.rs
- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/matchers/name.rs
- src/find/matchers/perm.rs
- src/find/matchers/printf.rs
- src/find/matchers/regex.rs
- src/find/matchers/size.rs
- src/find/matchers/time.rs
- src/find/matchers/type_matcher.rs
- src/find/mod.rs
- src/xargs/mod.rs
- tests/common/test_helpers.rs
- tests/find_cmd_tests.rs
- tests/xargs_tests.rs
Done with:
$ cargo +nightly clippy --tests --fix --allow-dirty -- -W clippy::pedantic
> Run clippy pedantic fixes

- src/find/matchers/mod.rs
- src/find/matchers/time.rs
- src/find/mod.rs
link: https://github.com/uutils/findutils/issues/307
> find: Implement `-newerXY`

- src/find/matchers/mod.rs
- tests/find_cmd_tests.rs
fix: https://github.com/uutils/findutils/issues/29
This commit modifies a test function `build_top_level_matcher_too_many_brackets` outside of my code, 
which tests that `find -true \( \) \)` will return a `too many ')'` error.
But in GNU find, this instruction will first cause an `empty parentheses are not allowed` error, 
so it is changed to `find . -type f \( -name "*.txt" \) \)` to maintain compatibility.
> find: Fix unexpectedly accepted empty expression.

- src/find/matchers/time.rs
- src/find/mod.rs
I'm sorry that I wrote some redundant code at https://github.com/uutils/findutils/pull/353 and https://github.com/uutils/findutils/pull/342 which caused `cargo clippy --all-targets --all-features` to generate multiple warnings.
Fix them in this PR.
> clippy: Fix clippy warning.

- src/find/matchers/mod.rs
- tests/find_cmd_tests.rs
convert_arg_to_comparable_value() as mentioned in https://github.com/uutils/findutils/pull/355#issuecomment-2067613423 parses some strange characters. 
The original regular expression was `([+-]?)(\d+)$` , which did a partial match and only included `1%2` of `2` as part of the match. 
After adding the `^` limiter (`^([+-]?)(\d+)$`), the expression can be restricted to only match `+` `-` or `0-9`.
> find: Fix `convert_arg_to_comparable_value()` function parsing unexpected characters.

- src/find/mod.rs
This PR replaces the use of `zip` with nested loops because it was mistakenly assumed that `zip` creates the Cartesian product of two lists.
> find: replace `zip` with nested loops in tests

- src/find/matchers/mod.rs
- src/find/matchers/time.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
implement: https://github.com/uutils/findutils/issues/370
Added extra judgment to `parse_str_to_newer_args()` function.
1. `-anewer` is equivalent to `-neweram`
2. `-cnewer` is equivalent to `-newercm`
3. `-newer` is equicalent to `-newermm`
BFS test `+1 PASS` in commit 57f2a3bc0751f617933f551a531bdf45acdf77fd.
This PR **does not** solve [Parsing multiple time formats](https://github.com/uutils/findutils/issues/384), I will open a new PR to handle it separately. : )
> find: Implement `-anewer` and `-cnewer`.

- .github/workflows/ci.yml
I noticed that while we have jobs named "cargo test" in the CI, they don't run `cargo test` but `cargo check`, and are almost identical to the "cargo check" jobs. This PR runs `cargo test` instead of `cargo check` in the "cargo test" jobs.
> ci: run `cargo test` instead of `cargo check` in "cargo test" jobs

- src/xargs/mod.rs
This PR adds `#[allow(dead_code)]` to the `CommandExecutionError` enum to avoid a "variant `Killed` is never constructed" warning on Windows (see, for example, https://github.com/uutils/findutils/actions/runs/9298475960/job/25590452513?pr=395#step:6:201).
> xargs: use `#[allow(dead_code)]` for enum

- src/find/mod.rs
This PR removes an unused import on Windows to fix the corresponding warning (see, for example, https://github.com/uutils/findutils/actions/runs/9285549600/job/25550305051#step:6:232).
> find: remove unused import on Windows

- src/find/matchers/time.rs
- src/find/mod.rs
1. Using `fs::remove_file` in Windows platform tests may return an `Ok()` even [if the file is not deleted immediately](https://doc.rust-lang.org/std/fs/fn.remove_file.html), which will cause an error in the code in the test that assumes the file is deleted.
2. In another test code, some `/` separators were accidentally escaped as `\\`. Now it has been changed to use `contains` to determine whether the output contains a specific path and ignore the path separator problem.
> find: Fix `-newerXY` test code for Windows platform.

- src/find/matchers/mod.rs
- src/find/matchers/time.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
implement: https://github.com/uutils/findutils/issues/221
> find: Implement `-amin` `-cmin` `-mmin` age ranges.

- src/find/matchers/mod.rs
- src/find/mod.rs
This PR fixes clippy warnings from the [legacy_numeric_constants](https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants) lint introduced with Rust 1.79.
> find: fix usage of legacy numeric methods

- src/xargs/mod.rs
- tests/xargs_tests.rs
Resolves #362
- If `-I`/`-i`/`--replace` is given, now we process extra args (read from stdin) _one by one_, and replace all matches in initial args (given in argv) with the same extra arg in each time. (i.e. Cartesian product)
```shell
$ printf 'a    bc\ndef\ng' | xargs -I _ echo '[_]'
[a bc def g]
$ printf 'a    bc\ndef\ng' | cargo run --bin xargs -- -I _ echo '[_]'
[a    bc]
[def]
[g]
```
- `-L` (`--max-lines`), `-n` (`--max-args`) and `-I`/`-i` are mutually exclusive. Now we warn if more than one are given.
> xargs: do not merge extra args before replacing

- Cargo.lock
- Cargo.toml
This PR bumps `regex` from `1.7` to `1.10` and as a result `byteorder` is no longer needed.
> Bump regex from 1.7 to 1.10

- src/find/matchers/mod.rs
- src/find/matchers/stat.rs
- tests/find_cmd_tests.rs
This PR is a refactoring that makes the implementations of `InodeMatcher` and `LinksMatcher` unix-only. And moves the error handling for other platforms to where we handle `-inum` and `-links`.
The refactoring is done to get rid of two "field x is never read" warnings on Windows (see, for example, https://github.com/uutils/findutils/actions/runs/9271426702/job/25506758917#step:6:185)
> find: make `InodeMatcher` & `LinksMatcher` unix-only

- src/find/matchers/mod.rs
- src/find/matchers/samefile.rs
- tests/find_cmd_tests.rs
implement: https://github.com/uutils/findutils/issues/373
BFS test `+1 PASS` and GNU test `PASS +8` / `FAIL -20` in commit bc8ae9859ef41b21a67ab0b72143751240659e3a
> find: Implement `-samefile`

- Cargo.toml
- src/find/matchers/fs.rs
- src/find/matchers/mod.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
link: https://github.com/uutils/findutils/issues/374
> find: Implement `-fstype`

- .github/workflows/comment.yml
- util/compare_bfs_result.py
- util/compare_gnu_result.py
Tested in fork, this change may still only take effect after being merged.
> Comments are only sent when GNU/BFS test compatibility changes.

- src/find/matchers/mod.rs
- src/find/matchers/samefile.rs
- tests/find_cmd_tests.rs
> samefile: Cache FileInformation for the target

- src/find/matchers/fs.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
Fix #418.
Before:
```
Benchmark 1: find ~/Workspace -fstype xfs
Time (mean ± σ):     195.8 ms ±   3.2 ms    [User: 34.7 ms, System: 160.7 ms]
Range (min … max):   192.4 ms … 202.4 ms    14 runs
Benchmark 2: target/release/find ~/Workspace -fstype xfs
Time (mean ± σ):     12.494 s ±  0.098 s    [User: 2.645 s, System: 8.936 s]
Range (min … max):   12.318 s … 12.670 s    10 runs
Summary
find ~/Workspace -fstype xfs ran
63.80 ± 1.16 times faster than target/release/find ~/Workspace -fstype xfs
```
After:
```
Benchmark 1: find ~/Workspace -fstype xfs
Time (mean ± σ):     190.7 ms ±   3.4 ms    [User: 30.6 ms, System: 159.8 ms]
Range (min … max):   186.9 ms … 198.0 ms    15 runs
Benchmark 2: target/release/find ~/Workspace -fstype xfs
Time (mean ± σ):     284.1 ms ±   3.2 ms    [User: 67.8 ms, …
```
> Implement simple caching for -fstype

- src/find/matchers/exec.rs
This PR fixes a warning from the [needless_borrows_for_generic_args](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_borrows_for_generic_args) lint.
> find: fix needless borrow clippy warning

- .github/workflows/compat.yml
- util/build-bfs.sh
- util/diff-bfs.sh
And fix diff-bfs.sh for the new test result format.
> ci: Update bfs to 4.0

- src/find/matchers/ls.rs
- src/find/matchers/mod.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
> Implement `-ls` and `-fls`

- src/find/matchers/printf.rs
This PR fixes a warning from the [manual_pattern_char_comparison](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_pattern_char_comparison) lint introduced with Rust 1.81.
> find: use array instead of closure

- src/find/matchers/mod.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
> Implement `-fprint0`

- src/find/matchers/mod.rs
- src/find/matchers/printf.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
> Implement `-fprintf`

- src/find/matchers/glob.rs
The oniguruma version built by onig_sys does not include the commit
6f7b0aa ("add ONIG_SYN_BRE_ANCHOR_AT_EDGE_OF_SUBEXP into
ONIG_SYNTAX_POSIX_BASIC and ONIG_SYNTAX_GREP"), causing `$.` to actually
match a literal newline.
Using `$.` is not portable anyway; POSIX says
> A &lt;dollar-sign> ( '$' ) shall be an anchor when used as the last
> character of an entire BRE.
> find/glob: Don't use `$.` as a non-matching regex

- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/matchers/prune.rs
This PR fixes some new clippy warnings from the [needless_lifetimes](https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes) and [empty_line_after_outer_attr](https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_outer_attr) lints.
> find: fix new clippy warnings

- .github/workflows/compat.yml
- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/matchers/prune.rs
Closed #483 #463
- Replace the `Enable sources & install dependencies` step with the enable deb-src sources instructions for Ubuntu 24.04. #483
- Remove the `dawidd6/action-download-artifact@v6` component and use js to access the GitHub API to download the artifact. #463
- Fix several issues with `cargo clippy --all-targets -- -D warnings`.
> ci: Fix issues related to downloading builds in ci.

- src/find/matchers/fs.rs
This PR fixes an "unused import" warning on Windows, see, for example, https://github.com/uutils/findutils/actions/runs/13512703858/job/37755835852?pr=496#step:6:181.
> find: fix "unused import" warning on Windows

- Cargo.lock
This PR removes two of the three `windows-sys` versions by upgrading the following dependencies:
* `anstream` from `0.6.12` to `0.6.18`
* `anstyle-query` from `1.0.0` to `1.1.2`
* `anstyle-wincon` from `3.0.1` to `3.0.7`
* `parking_lot_core` from `0.9.9` to `0.9.10`
* `winapi-util` from `0.1.8` to `0.1.9`
> Bump dependencies to remove two `windows-sys` versions

- Cargo.lock
- Cargo.toml
This PR removes the `once_cell` dependency as we no longer use it as a direct dependency.
> Remove unused `once_cell` dependency

- src/find/matchers/name.rs
As stated by @tavianator, the correct behavior of -name / is:
```
$ find / -maxdepth 0 -name /
/
$ find /// -maxdepth 0 -name /
///
$ find / -maxdepth 0 -name ///
$ find /// -maxdepth 0 -name ///
```
This PR meets the specified requirements. Now the issue https://github.com/uutils/findutils/issues/24 can be closed.
> Fix incorrect triple slashes behavior

- src/find/matchers/ls.rs
- src/find/matchers/printer.rs
The uucore function has the downside of leaking the failure state
between unrelated tests, because the exit code is global.  PR #436
introduced a method on MatcherIO which solves the problem, but future
PRs added new uses of uucore::error::set_exit_code().
> find: Use matcher_io.set_exit_code()

- Cargo.lock
- Cargo.toml
- src/find/matchers/exec.rs
- src/find/matchers/logical_matchers.rs
- src/find/matchers/mod.rs
- src/find/mod.rs
- tests/exec_unit_tests.rs
- tests/find_exec_tests.rs
This PR implements `-exec ... {} +` with [argmax](https://crates.io/crates/argmax) as a new dependency.
Solve #6 , #366
> find: Implement exec[dir] +

- src/testing/commandline/main.rs
- tests/find_exec_tests.rs
These tests failed on my system because directory entries were returned
in a different order, causing an output mismatch.  Add --sort to the
testing_commandline to make the output deterministic.
> tests: Make -exec {} + tests deterministic

- src/find/matchers/entry.rs
- src/find/matchers/printf.rs
- src/xargs/mod.rs
This PR fixes warnings from the [manual_div_ceil](https://rust-lang.github.io/rust-clippy/master/index.html#manual_div_ceil) and [double_ended_iterator_last](https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last) lints.
> clippy: fix warnings from Rust 1.86

- src/find/matchers/entry.rs
- src/find/matchers/type_matcher.rs
- tests/find_cmd_tests.rs
Refer - https://www.gnu.org/software/findutils/manual/html_node/find_html/Type.html
>As a GNU extension, multiple file types can be provided as a combined list separated by comma ‘,’. For example, ‘-type f,d,l’ is logically interpreted as ‘( -type f -o -type d -o -type l )’.
> Implement : Chained Type matcher arguments

- src/find/matchers/mod.rs
- src/find/mod.rs
- tests/find_cmd_tests.rs
Changed the error format of 
```Error: .......```
to
```find: .......```
to match GNU and also help pass testsuite.
Also fixed an error message which was failing test in GNU Testsuite and it is now passing (`tests/find/user-group-max.sh`)
> change "Error:" to "find:" + Testcase fix

- CONTRIBUTING.md
The link in the documentation to the Git book has changed.
> docs: update dead link

- .github/workflows/release.yml
- dist-workspace.toml
This PR uses `ubuntu-latest` instead of `ubuntu-20.04` in the `release` workflow. `ubuntu-20.04` has been removed from Github according to https://github.com/actions/runner-images/issues/11101 .
Please note that `release.yml` is usually auto-generated by `dist`. However, the changes of this PR are done manually as there is no newer version of `dist` available. The future of the project is currently unclear as the company behind it apparently run into financial problems.
Thanks to @Qelxiros who mentioned this issue in https://github.com/uutils/findutils/pull/536#issuecomment-2808407853 !
> ci: use `ubuntu-latest` instead of `ubuntu-20.04` for `release` workflow

- Cargo.lock
- Cargo.toml
This PR manually bumps `uucore` from `0.0.30` to `0.1.0`. For some reason dependabot didn't create a PR :|
> Bump `uucore` from `0.0.30` to `0.1.0`
